/* Approved paths and campaign labels only. Do not add submitted form values here. */
window.CrawledConfig = Object.freeze({
  // Property decision pending. Preserve historical destinations once per page.
  defaultAnalyticsIds: ['G-XP7L167LNN', 'G-158F1ZSV4K'],
  localAnalyticsIds: ['G-XP7L167LNN'],
  approvedPaths: ["/about/","/audit/","/blog/10-practical-generative-engine-optimization-geo-strategies-a-step-by-step-playbook/","/blog/7-reasons-to-add-a-blog-section-to-your-website/","/blog/a-geo-audit-12-signals-generative-engines-use-to-decide-whether-youre-worth-showing/","/blog/ai-crawlers-robots-txt-guide/","/blog/ai-search-optimization-in-2026-why-traditional-seo-alone-no-longer-protects-your-visibility/","/blog/entity-seo-and-brand-authority/","/blog/from-localhost-to-first-sale-a-non-marketers-guide-to-launching-on-product-hunt/","/blog/from-seo-to-geo-how-to-rank-or-get-cited-in-the-age-of-ai-answer-engines/","/blog/generative-engine-optimization-geo-what-a-new-academic-study-reveals-about-the-future-of-search/","/blog/google-search-cheat-sheet-operators-url-tricks-and-smarter-search-tips/","/blog/google-shifts-the-web-shivers-what-this-months-volatility-signals-for-seo-and-geo/","/blog/how-ai-visibility-really-works-and-whats-worth-paying-attention-to/","/blog/how-geo-could-replace-seo-in-an-ai-native-web/","/blog/how-seos-can-engineer-product-demand-inside-googles-ai-overview/","/blog/how-to-add-a-paywall-to-an-ai-built-app-without-a-backend-the-minimal-code-guide/","/blog/how-to-get-your-first-10-paying-users-from-reddit-without-getting-banned/","/blog/how-to-rank-an-ai-app-on-google-with-zero-ad-spend/","/blog/how-to-structure-free-tiers-and-paid-gates-for-ai-generated-apps/","/blog/how-to-track-ai-search-visibility/","/blog/how-to-track-saas-conversions-on-vercel-using-posthog-and-google-search-console/","/blog/how-to-write-content-ai-search-cites/","/blog/","/blog/inside-the-manufactured-web-how-fake-reviews-are-warping-online-trust/","/blog/lifetime-deals-vs-monthly-subscriptions-how-to-price-your-first-micro-saas-app/","/blog/llms-txt-explained/","/blog/local-seo-and-ai-search/","/blog/merchant-of-record-vs-payment-gateway-why-indie-hackers-are-choosing-lemon-squeezy-over-stripe-in-2026/","/blog/programmatic-seo-101-how-solo-builders-generate-high-intent-organic-traffic/","/blog/schema-markup-for-ai-search/","/blog/stripe-checkout-vs-paddle-vs-lemon-squeezy-the-ultimate-saas-pricing-and-tax-comparison/","/blog/the-29-lifetime-deal-strategy-how-solo-builders-cash-flow-their-first-1000/","/blog/the-build-in-public-marketing-playbook-for-solo-developers-and-vibe-coders/","/blog/the-geo-lexicon/","/blog/the-new-layer-of-search-how-llms-interpret-context/","/blog/topic-clusters-and-internal-linking/","/blog/troll-farms-ai-and-the-engineering-of-public-opinion/","/blog/what-is-crawled/","/blog/what-is-crawling-in-seo-why-it-is-the-first-signal-in-generative-engine-optimization/","/blog/why-seo-matters-more-in-2026-than-ever-before/","/blog/why-the-february-2026-google-update-feels-like-a-ranking-drop/","/case-studies/hvacrai/","/case-studies/","/faqs/","/florence-al-seo/","/guides/ai-search-visibility/","/","/local/","/nelte-law-schema/","/packages/","/privacy/","/terms/","/video/","/software-seo/"],
  campaigns: {
    utm_source: ['flyer-a', 'flyer-b', 'video', 'business_card', 'flyer_a', 'flyer_b'],
    utm_medium: ['qr', 'social'],
    utm_campaign: ['local']
  }
});

